name: $(BuildDefinitionName)_CI_$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)
trigger:
- master
- dev

pool:
  vmImage: ubuntu-16.04

variables:
  assemblyVersion:     '1.0.0' # assembly version needs to be incremented here
  revision:            $[counter('simple-v1-revision', 0)]
  isMasterBranch:      $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  
  imageReference: 'demokcr.azurecr.io/simple'
  
stages:

- stage: Docker
  dependsOn: ''
  condition: eq(variables.isMasterBranch, true)
  jobs:
  - job: ImagePush
    displayName: Build and push docker images
    steps:

      - task: CmdLine@2
        displayName: Build and push docker images
        env:
          PACKAGE_VERSION: $(assemblyVersion).$(revision)
          LOGIN_USERNAME: 'DemoKcr'
          LOGIN_PASSWORD: 'y9ytfhh7US5Oa7Ta6nyfg=pbyOeQ/mEe'
          LOGIN_HOSTNAME: 'demokcr.azurecr.io'
        inputs:
          workingDirectory: '/'
          failOnStderr: false
          script: |
            :: push av image
            TAGGED_IMAGE="$LOGIN_HOSTNAME/av:$PACKAGE_VERSION"
            echo "$LOGIN_PASSWORD" | docker login --username $LOGIN_USERNAME --password-stdin $LOGIN_HOSTNAME
            docker build -t $TAGGED_IMAGE -f azure-vote/Dockerfile .
            docker push $TAGGED_IMAGE
            docker rmi $TAGGED_IMAGE
